### ISSUE TITLE
Since there are no keyframes, is there a way to remove a finished animation and attach a new one?

### ISSUE THREAD

**Issue by pegasusnotunicorn** [jscottsmith/react-scroll-parallax#132] opened 2022-02-05 07:34 UTC
I would love to use something like keyframes to make complex animations but it doesn't seem like this library supports that. 

Is there a way that maybe we can remove the Parallax animation once its completed and attach a new one? Maybe like an event handler or something.

Thank you!

**Comment by jscottsmith** [comment] 2022-02-05 19:49
@pegasusnotunicorn it doesn't yet. There seems to be some interest in such a feature so I may support it in the future.

Currently the least hacky way I can think of achieving such effects is mocked up in this [CodeSandbox](https://codesandbox.io/s/react-scroll-parallax-chaining-effects-4h7dh?file=/src/ChainedEffects.tsx). Basically I'm using to effects with different animations that happen in sequence. Honestly wouldn't recommend it though, probably some edge cases that would break expected behaviors.

Can you describe your use case for me so I can consider it for a future change to the API to support keyframes?

**Comment by pegasusnotunicorn** [comment] 2022-02-05 20:01
Yeah I was thinking about this some more after posting it. I figured it would have to use separate start/end scroll values to accomplish. 

Well for my use-case, I want the element to animate, then maybe stick with the scroll (position fixed) for a bit, then animate out of view in a different way. 

Might have to play around with using the callbacks and merge the animations and pause it at halfway or something like that. Hope I am explaining this correctly lol.

**Comment by jscottsmith** [comment] 2022-02-05 21:04
Ya that could work. If you end up making it work post the code in case anyone else tries the same thing. You could also just use [ScrollTrigger by GSAP] - might seem overkill but probably more suited for something like this. 

I'll keep thinking on how to adapt the API for keyframes.

**Comment by pegasusnotunicorn** [comment] 2022-02-05 23:04
I thought onExit was only called when the element left the viewport but it seems to also be called when you first load a page and any elements with this callback are not in view. So it's called even if you never entered an element before.

Might need to update the docs on this.

Found this by trying to stagger parallax animations with separate start/end scroll values

**Comment by jscottsmith** [comment] 2022-02-06 04:04
@pegasusnotunicorn thats a bug, you can track a fix here: https://github.com/jscottsmith/parallax-controller/issues/2

Thanks for catching it.

**Comment by jscottsmith** [comment] 2022-02-06 20:45
This should be fixed now, patch published in v3.0.3

**Comment by pegasusnotunicorn** [comment] 2022-02-07 05:24
> @pegasusnotunicorn it doesn't yet. There seems to be some interest in such a feature so I may support it in the future.
> 
> Currently the least hacky way I can think of achieving such effects is mocked up in this [CodeSandbox](https://codesandbox.io/s/react-scroll-parallax-chaining-effects-4h7dh?file=/src/ChainedEffects.tsx). Basically I'm using two effects with different animations that happen in sequence. Honestly wouldn't recommend it though, probably some edge cases that would break expected behaviors.
> 
> Can you describe your use case for me so I can consider it for a future change to the API to support keyframes?

So I'm trying to do multiple animations with separate start/end scrolls like in your CodeSandbox but it seems to bug out when scrolling really fast. It even bugs out for your CodeSandbox. Try scrolling like super fast and you'll see that the rectangle for a split second goes somewhere it shouldn't according to the animation.

You can also see it live on my website here - sharehomethegame.com. If I scroll too fast or even just change the tab the animations get wonky and the elements move to places it shouldn't be. Then if I slowly scroll again it jumps to where it should go.

Any idea what might be causing this?

Thank you so much!

**Comment by pegasusnotunicorn** [comment] 2022-02-07 05:25
It's so strange that even just something like changing tabs causes this issue

**Comment by pegasusnotunicorn** [comment] 2022-02-07 19:35
I'm testing on Chrome Version 98.0.4758.80 (Official Build) (x86_64)

Here is a GIF of what I am seeing on your CodeSandbox. See how around the 8s mark the rectangle appears a bit to the right when scrolling very fast. Even though it will never be there in the entire animation.

https://user-images.githubusercontent.com/58995656/152858967-8079a820-c2ad-4b58-bb5f-aada34a3a81d.mov

**Closed** 2022-02-10 22:32 UTC
Labels: support
